### ISSUE TITLE
安卓编译报错  error: use of undeclared identifier 'round'

### ISSUE THREAD

**Issue by andrewhuman** [moli232777144/mtcnn_ncnn#10]
用AS build 报错:
mtcnn_ncnn\mtcnn_AS\app\src\main\cpp\mtcnn.cpp

Error:(95, 27) error: use of undeclared identifier 'round'
Error:(96, 27) error: use of undeclared identifier 'round'
Error:(97, 27) error: use of undeclared identifier 'round'
Error:(98, 27) error: use of undeclared identifier 'round'
Error:(189, 24) error: use of undeclared identifier 'round'
Error:(190, 24) error: use of undeclared identifier 'round'
Error:(191, 24) error: use of undeclared identifier 'round'
Error:(192, 24) error: use of undeclared identifier 'round'
Error:(217, 23) error: use of undeclared identifier 'ceil'
Error:(218, 23) error: use of undeclared identifier 'ceil'

请问是什么原因，直接用AS打开mtcnn_as项目

**Comment by moli232777144** [comment]
已经安装了c++混编的LLDB，CMake 和 NDK等环境？有c++的库没链接到。

**Comment by andrewhuman** [comment]
检查过LLDB，CMake 和 NDK都安装好的 ，NDK 版本最新17.0.*，对NDK版本有要求吗

**Comment by andrewhuman** [comment]
@moli232777144

**Comment by wwmoo7** [comment]
#include <math.h>
