### ISSUE TITLE
mtcnn.cpp line 226报编译错误

### ISSUE THREAD

**Issue by gandaofu** [moli232777144/mtcnn_ncnn#11]
我试图移植到linux环境中，结果报如下错误
[ 33%] Building CXX object CMakeFiles/mtcnn_ncnn.dir/src/mtcnn.cpp.o
/root/ai/mtcnn_cnn/mtcnn_cnn/src/mtcnn.cpp: In member function ‘void MTCNN::RNet()’:
/root/ai/mtcnn_cnn/mtcnn_cnn/src/mtcnn.cpp:226:31: warning: pointer of type ‘void *’ used in arithmetic [-Wpointer-arith]
         if(*(score.data+score.cstep) > threshold[1]){
                               ^
/root/ai/mtcnn_cnn/mtcnn_cnn/src/mtcnn.cpp:226:36: error: ‘void*’ is not a pointer-to-object type
         if(*(score.data+score.cstep) > threshold[1]){
                                    ^
CMakeFiles/mtcnn_ncnn.dir/build.make:62: recipe for target 'CMakeFiles/mtcnn_ncnn.dir/src/mtcnn.cpp.o' failed
make[2]: *** [CMakeFiles/mtcnn_ncnn.dir/src/mtcnn.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mtcnn_ncnn.dir/all' failed
make[1]: *** [CMakeFiles/mtcnn_ncnn.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by moli232777144** [comment]
您使用的ncnn是新版的数据结构，PC端暂未更新到新版，您可以参考安卓项目里的同名文件，修改报错相应位置的代码
