### ISSUE TITLE
检测时间

### ISSUE THREAD

**Issue by ycdhqzhiai** [moli232777144/mtcnn_ncnn#19]
海思960sample检测时间53ms，正常吗？

**Comment by moli232777144** [comment]
应该差不多，你可以循环多测试几次，多人脸第二、三阶时间就爆炸；MTCNN简单优化的点也不多，多图合并单图计算，batch计算(ncnn暂不支持)，缩小第三阶模型等；ncnn更新了int8，这个你可以先试试。
