### ISSUE TITLE
RNet输出结果为空

### ISSUE THREAD

**Issue by 791136190** [moli232777144/mtcnn_ncnn#2]
你好，有幸看到你的工程资源。环境安装完后，测试时p网络输出正常，r网络输出为空。你测试时是否一切正常？同时在mtcnn的226行（if(*(score.data+score.cstep) > threshold[1])），编译报错。此处应该需要将void*强转为float*。

**Comment by moli232777144** [comment]
恩，这些问题是ncnn作者修改了mat结构后产生的问题，当时调试的版本比较早，有空回头我会一起调试修改下，并重构优化下整个网络的逻辑结构。

**Comment by 791136190** [comment]
嗯，下午换到你之前使用的版本，已经可以获取到正确的结果，感谢回复

**Comment by xyt2008** [comment]
最新的ncnn版本确实在mtcnn中的RNet中不能返回结果。moli232777144 提供的ncnn版本可以。试着改了下输出部分的表示形式发现无论是使用if ((float)score.channel(1)[0] > threshold[1]) 还是if(*(float*)(score.data+score.cstep) > threshold[1])都不行。使用最新的ncnn版本mtcnn.cpp要怎么改呢？

**Comment by ChenjingYu1993** [comment]
请教一下，这里获取score时候，为什么取得是channel[1]，而不是从channel[0]?
