### ISSUE TITLE
自己用caffe 训练的mtcnn ，在caffe 上能正常使用，转为ncnn 后不能检测到人脸

### ISSUE THREAD

**Issue by grainw** [moli232777144/mtcnn_ncnn#21]
自己用caffe 训练的mtcnn ，在caffe 上能正常使用，转为ncnn 后，使用项目中提供的程序不能检测到人脸，请问什么地方会有不同吗？

**Comment by moli232777144** [comment]
这是原版MATLAB的mtcnn，自己训练的，查下输出层名字，还有BGR和RGB差异

**Comment by ltcs11** [comment]
请问model中的caffe模型是MATLAB训练产生的吗？
我在python API下调用caffemodel后， caffe输出的结果与ncnn输出的结果存在一定的差距
