### ISSUE TITLE
mtcnn 的输入能用灰度图吗？

### ISSUE THREAD

**Issue by hao201707** [moli232777144/mtcnn_ncnn#22]
我想提高检测速度，考虑输入灰度图，但是检测不出人脸了！如果要支持灰度图，需要做什么改变？
ncnn::Mat gray_img = ncnn::Mat::from_pixels((const unsigned char*)(ncnn_img.data), ncnn::Mat::PIXEL_BGR2GRAY, width, height);

**Comment by moli232777144** [comment]
不支持
