### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by chongchuanbing** [moli232777144/mtcnn_ncnn#24]
vs2017 + opencv3.2
错误	C2065	“t”: 未声明的标识符	mtcnn_ncnn	E:\dev\workspace\mtcnn_ncnn\3rdparty\include\Opencv\opencv2\core\fast_math.hpp	97	

错误	C2065	“__m128d”: 未声明的标识符	mtcnn_ncnn	E:\dev\opencv3.4.3\build\include\opencv2\core\fast_math.hpp	105	

错误	C3861	“_mm_cmplt_sd”: 找不到标识符	mtcnn_ncnn	E:\dev\workspace\mtcnn_ncnn\3rdparty\include\Opencv\opencv2\core\fast_math.hpp	136	

切换 vs2017 + opencv3.4.3， 问题依旧。。。

不知道什么错，c++小白，请求帮助，感谢！！！

**Comment by jiangfan2** [comment]
我也遇到同样问题，请问楼主解决了吗？

**Comment by moli232777144** [comment]
opencv的include头文件换你们自己用的版本里面的

**Comment by jiangfan2** [comment]
open换成自己环境的opencv3.2.0的了，仍然同样的错误。
opencv3.2.0是自己编译的，包括examples全部编译过，examples里的不知哪个会引用fast_math.hpp

**Comment by jiangfan2** [comment]
我把 main.cpp的头文件挪了顺序行了：
#include "opencv2/core.hpp"
#include <opencv2/opencv.hpp>
#include "mtcnn.h"
。。。
