### ISSUE TITLE
ncnn.bat运行的时候报错？Protobuf compiler version 3.5.0 doesn't match library version

### ISSUE THREAD

**Issue by zhangtao22** [moli232777144/mtcnn_ncnn#25]
CMake Warning at C:/Program Files/CMake/share/cmake-3.13/Modules/FindProtobuf.cmake:499 (message):
  Protobuf compiler version 3.5.0 doesn't match library version
  ERROR.ERROR.ERROR
Call Stack (most recent call first):
  tools/onnx/CMakeLists.txt:2 (find_package)

-- Configuring incomplete, errors occurred!

请问你们用的cmake是什么版本啊？有没有遇到我这个问题

**Comment by moli232777144** [comment]
cmake version 3.9.0-rc3

更高的版本应该没啥影响，这个看起来是你protobuf编译的问题，你试下重新链接编译看看。

**Comment by zhangtao22** [comment]
我删了重新弄了一下，可以了
