### ISSUE TITLE
您好，我在cmake ncnn时，缺少cmakelist.txt文件？

### ISSUE THREAD

**Issue by Jay-Liu** [moli232777144/mtcnn_ncnn#26]
cmake .. -G"Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%cd%/install -DProtobuf_INCLUDE_DIR=F:\mtcnn_ncnn\3rdparty\include -DProtobuf_LIBRARIES=F:\mtcnn_ncnn\3rdparty\lib\libprotobuf.lib -DProtobuf_PROTOC_EXECUTABLE=F:\mtcnn_ncnn\3rdparty\bin\protoc.exe
作者您好，我在这一步中，显示没有CMakeList？确实没有CMakeList，怎么编译啊？

**Comment by moli232777144** [comment]
工程目录下有CMakeList，..代表是上级目录，确认下你操作的当前目录。

**Comment by Jay-Liu** [comment]
谢谢您的回复，我确定了我的当前目录没有错误，D:\mtcnn_ncnn-master\mtcnn_ncnn-master\3rdparty\src\ncnn\build，其中ncnn中没有CMakeList文件?
