### ISSUE TITLE
安卓端实时检测

### ISSUE THREAD

**Issue by YjDai** [moli232777144/mtcnn_ncnn#4]
@moli232777144  你好，看了你的代码，写的很详细，想问一下，安卓端你实现了摄像头实时检测了吗？怎么来验证呢？

**Comment by moli232777144** [comment]
摄像头实时检测，是类似的接口，主要是适配问题，需增加yuv420sp转rgb格式，以及摄像头数据转置的角度，后续写人脸跟踪范例会考虑更新。

**Comment by YjDai** [comment]
@moli232777144 好的，谢谢，期待你的范例~~

**Comment by YjDai** [comment]
@moli232777144 ncnn提供线程数控制接口，可以多核加速，想问一下，接口在哪里体现呀？

**Comment by moli232777144** [comment]
没写这么细，三个网络都有一个set_num_threads，统一加个参数，设置下接口就可以。

**Comment by YjDai** [comment]
@moli232777144 ，是的看到啦，但是发现，设置的线程数越多，反而越慢呢，奇怪

**Comment by moli232777144** [comment]
跟你cpu核数有关，是否大小核，还有线程部属都有关系，MTCNN这个算法还是有挺多问题的，级联的算法速度都不太稳定。

**Comment by wangzl2011** [comment]
实时人脸识别 运行一段时间会报这个错

报错代码 mtcnn->detect(ncnn_img, finalBbox);

错误信息：

-18524/com.test.mtcnn A/libc: invalid address or address of corrupt block 0x50504f8 passed to dlfree
11-11 10:24:05.882 18524-18524/com.test.mtcnn A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdeadbaad in tid 18524 (.test.mtcnn)

@moli232777144 求指点

**Comment by moli232777144** [comment]
AS简单看下内存占用情况，检测看看内存泄漏没

**Comment by wangzl2011** [comment]
内存应该泄漏了 有什么解决方案吗

**Comment by moli232777144** [comment]
一般是你代码的问题，初步检测new和malloc等操作，vs下先用VLD工具测试下，JNI一些回调的内存泄漏就不太好查。
