### ISSUE TITLE
请问MTCNN

### ISSUE THREAD

**Issue by flankechen** [moli232777144/mtcnn_ncnn#9]
你好，请问MTCNN现在用到的caffe models是哪里来的？有训练代码吗？
我原来用tensorflow，不知道这个caffe的训练结果是哪里来的。
谢谢！

**Comment by moli232777144** [comment]
[MTCNN](https://github.com/kpzhang93/MTCNN_face_detection_alignment)原作者开源的模型，无训练源码

**Comment by flankechen** [comment]
@moli232777144 明白了，sad， 谢谢！
